name: Release binary
on: 
  push:
    branches: main
jobs:
  minimal:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          extra_nix_config: |
            substituters = https://cache.nixos.org https://static-haskell-nix.cachix.org
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= static-haskell-nix.cachix.org-1:Q17HawmAwaM1/BfIxaEDKAxwTOyRVhPG5Ji9K3+FvUU=
          install_url: https://nixos.org/releases/nix/nix-2.0.4/install
      - name: Build
        run: nix build
      - name: Move
        run: cp ./result/bin/LiarsDice liarsdice
      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: "latest"
          prerelease: false
          title: "Current binary"
          files: liarsdice
