name: Release binary
on: 
  push:
    branches: main
jobs:
  minimal:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install nix
        uses: nixbuild/nix-quick-install-action@v25
      - name: Build
        run: nix build
      - name: Move
        run: cp ./result/bin/LiarsDice liarsdice
      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: "latest"
          prerelease: false
          title: "Current binary"
          files: liarsdice
